### ISSUE TITLE
[Traceback] Guideline could not be found

### ISSUE THREAD

**Issue by ryanbugden** [ryanbugden/Edit-Font-Dimensions#9]
Getting this traceback. Have two ~3000-glyph UFOs open at the same time.

```
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 165, in callObserver_withMethod_forEvent_withInfo_
  File "edit_font_dimensions.py", line 165, in glyph_window_did_open
  File "edit_font_dimensions.py", line 116, in remove_all_guides
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/fontParts/base/font.py", line 1367, in removeGuideline
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/fontParts/base/font.py", line 1288, in _getGuidelineIndex
fontParts.base.errors.FontPartsError: The guideline could not be found.
```

**Comment by ryanbugden** [comment]
Closing for now
